</$objtype/mkfile
BIN=/$objtype/bin

TARG=vts
OFILES=\
	main.$O\
	srv.$O\
	session.$O\
	cells.$O\
	celldiff.$O\
	engine.$O\
	lined.$O\

HFILES=dat.h\
	fns.h\
	cells.h\
	celldiff.h\
	compat.h\
	engine.h\
	session.h\
	lined.h\

</sys/src/cmd/mkone

$O.out:	/$objtype/lib/libvterm.a /$objtype/lib/lib9p.a /$objtype/lib/libthread.a /$objtype/lib/libc.a
