# plan9: hand-authored sysconfig data for the 9front CPython port. configure
# normally generates this; we bypass configure, so provide the config vars the
# stdlib (sysconfig, test.support, sysconfig-driven tests) reads at runtime.
build_time_vars = {
    'VERSION': '3.11',
    'prefix': '/sys/lib/python',
    'exec_prefix': '/sys/lib/python',
    'installed_base': '/sys/lib/python',
    'installed_platbase': '/sys/lib/python',
    'platbase': '/sys/lib/python',
    'PLATLIBDIR': 'lib',
    'LIBDIR': '/sys/lib/python/lib',
    'BINDIR': '/sys/lib/python/bin',
    'INCLUDEPY': '/sys/lib/python/include/python3.11',
    'PLATFORM': 'plan9',
    'MULTIARCH': '',
    'ABIFLAGS': '',
    'SOABI': 'cpython-311-plan9',
    'EXT_SUFFIX': '.so',
    'SHLIB_SUFFIX': '.so',
    'SO': '.so',
    'Py_ENABLE_SHARED': 0,
    'Py_DEBUG': 0,
    'WITH_PYMALLOC': 1,
    'WITH_DOC_STRINGS': 1,
    'CC': 'pcc',
    'CXX': 'pcc',
    'CFLAGS': '',
    'CCSHARED': '',
    'CONFIGURE_CFLAGS': '',
    'CONFIGURE_CPPFLAGS': '',
    'CONFIGURE_LDFLAGS': '',
    'OPT': '',
    'BASECFLAGS': '',
    'LDFLAGS': '',
    'LDSHARED': 'pcc -shared',
    'BLDSHARED': 'pcc -shared',
    'CCSHARED': '',
    'LINKFORSHARED': '',
    'LIBS': '',
    'SYSLIBS': '',
    'LDLIBRARY': '',
    'LIBRARY': 'libpython3.11.a',
    'AR': 'ar',
    'ARFLAGS': 'rc',
    'EXE': '',
    'SIZEOF_VOID_P': 8,
    'SIZEOF_SIZE_T': 4,
    'SIZEOF_LONG': 4,
    'MACHDEP': 'plan9',
    'HOST_GNU_TYPE': 'amd64-plan9',
    'BUILD_GNU_TYPE': 'amd64-plan9',
    'srcdir': '/sys/lib/python',
    'abs_srcdir': '/sys/lib/python',
    'abs_builddir': '/sys/lib/python',
    'PYTHONFRAMEWORK': '',
    'PYTHONFRAMEWORKDIR': 'no-framework',
    'PYTHONFRAMEWORKPREFIX': '',
    'PYTHONFRAMEWORKINSTALLDIR': '',
}
