#!/bin/bash
# asmint-spike.sh — M0b: prove the AsmInt generated-assembly LibJS interpreter
# is Plan 9-viable, without the VM (that's M1). Steps A1-A6 of the plan.
#
# Result 2026-07-15 (pin 8cc5d7a5ff), bare-metal cirno:
#   - asmintgen --arch x86_64 --object-format elf generates 8047 lines
#   - cc9-c++ assembles it clean: 184 handlers + asm_interpreter_entry
#   - audit: ZERO %fs/%gs (no TLS), ZERO red-zone rsp accesses (explicit
#     frame; VM ptr spilled at -0x30(%rbp) inside it), ZERO syscalls,
#     sections .text/.data.rel.ro/.eh_frame all placed by cc9/test/plan9.ld
#   - links into a Plan 9 a.out with 180 slow-path externs stubbed;
#     on-box: "entry=0x2000b0 first-byte=0x55 OK"
#
# Remaining before M1: the asm_offsets static_assert gate (offsets were
# generated by the HOST gen_asm_offsets — ARM64 macOS LP64; every offset must
# be re-proven against the cc9 x86_64 ABI once LibJS headers compile under
# cc9, i.e. after AK_OS_PLAN9 lands). Any mismatch = regenerate offsets via a
# cc9-compiled gen_asm_offsets run ON the box.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
LB="$HERE/../.."                                # ladybird9/
SRC="$LB/vendor/ladybird"
OUT="$LB/_out/asmint"; mkdir -p "$OUT"
CC9=/Users/claw/Projects/agent9/cc9
CC9CC=/Users/claw/Projects/agent9/servo9/host/cc9-cc
LLVM=/opt/homebrew/opt/llvm/bin

# A1: the generator (host rustc, host triple — it's a text tool)
cargo build --release --manifest-path "$SRC/Libraries/LibJS/AsmIntGen/Cargo.toml"
GEN="$SRC/Libraries/LibJS/AsmIntGen/target/release/asmintgen"

# A2: offsets — borrowed from the host reference build (LP64; re-proven by the
# static_assert gate at M1). Host build must have run: Meta/ladybird.py build js
OFFS="$SRC/Build/release/Libraries/LibJS/Bytecode/AsmInterpreter/asm_offsets.conf"
[ -f "$OFFS" ] || { echo "run the host reference build first"; exit 1; }

# A3: generate the x86_64 ELF flavor
"$GEN" --arch x86_64 --object-format elf \
  --constants "$OFFS" \
  --bytecode-def "$SRC/Libraries/LibJS/Bytecode/Bytecode.def" \
  --input "$SRC/Libraries/LibJS/Bytecode/AsmInterpreter/asmint.asm" \
  --output "$OUT/asmint_x86_64.S"

# A4: assemble via cc9 + audit
"$CC9CC" -c "$OUT/asmint_x86_64.S" -o "$OUT/asmint_x86_64.o"
fs=$("$LLVM/llvm-objdump" -d "$OUT/asmint_x86_64.o" | grep -cE '%?fs:|%?gs:' || true)
rz=$("$LLVM/llvm-objdump" -d "$OUT/asmint_x86_64.o" | grep -cE '\-0x[0-9a-f]+\(%rsp\)' || true)
sc=$("$LLVM/llvm-objdump" -d "$OUT/asmint_x86_64.o" | grep -cE 'syscall' || true)
echo "audit: tls=$fs redzone=$rz syscalls=$sc (all must be 0)"
[ "$fs$rz$sc" = "000" ]

# A6: link smoke (stub the slow-path externs, print entry byte on-box)
"$LLVM/llvm-nm" -u "$OUT/asmint_x86_64.o" | awk '{print "void "$2"(void) {}"}' > "$OUT/stubs.c"
"$CC9CC" -c "$OUT/stubs.c" -o "$OUT/stubs.o"
"$CC9CC" -c "$HERE/asmint_smoke.c" -o "$OUT/asmint_smoke.o"
"$(brew --prefix lld)/bin/ld.lld" -o "$OUT/asmint_smoke.elf" \
  "$OUT/asmint_smoke.o" "$OUT/asmint_x86_64.o" "$OUT/stubs.o" \
  --start-group "$CC9/lib/libcc9cxx.a" "$CC9/lib/libcc9m.a" --end-group \
  -T "$CC9/test/plan9.ld" -static -nostdlib
python3 "$CC9/host/elf2aout.py" "$OUT/asmint_smoke.elf" "$OUT/asmint_smoke.aout"
echo "deliver with: python3 $LB/host/deliver9.py $OUT/asmint_smoke.aout <host> <port> lb9a"
echo "expect on-box: entry=0x... first-byte=0x55 OK"
