#!/usr/bin/env python3
"""
gen-offsets-check.py — A5: turn gen_asm_offsets.cpp + a host-generated
asm_offsets.conf into a compile-only static_assert TU. Compiling the result
with cc9-c++ PROVES every struct offset AsmInt was generated against matches
the cc9 x86_64 ABI (the offsets came from an ARM64-macOS LP64 host run; both
are LP64 SysV-layout, but parity is proven, not assumed).

Usage: gen-offsets-check.py <gen_asm_offsets.cpp> <asm_offsets.conf> <out.cpp>
"""
import re
import sys

src_path, conf_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
src = open(src_path).read()

vals = {}
for line in open(conf_path):
    m = re.match(r"const (\w+) = (\d+)", line)
    if m:
        vals[m.group(1)] = int(m.group(2))

includes = [l for l in src.splitlines() if l.startswith("#include")]

# EMIT_OFFSET(NAME, type, member) / EMIT_SIZEOF(NAME, type) — types may contain
# template commas, so split on top-level commas only.
def split_args(s):
    out, depth, cur = [], 0, ""
    for c in s:
        if c in "<(":
            depth += 1
        elif c in ">)":
            depth -= 1
        if c == "," and depth == 0:
            out.append(cur.strip())
            cur = ""
        else:
            cur += c
    out.append(cur.strip())
    return out

asserts = []
for m in re.finditer(r"EMIT_OFFSET\(([^;]+?)\);", src, re.S):
    name, ty, member = split_args(m.group(1))
    if name not in vals:
        print(f"warning: {name} not in conf", file=sys.stderr)
        continue
    asserts.append(f'static_assert(offsetof({ty}, {member}) == {vals[name]}, "{name}");')
for m in re.finditer(r"EMIT_SIZEOF\(([^;]+?)\);", src, re.S):
    name, ty = split_args(m.group(1))
    if name not in vals:
        print(f"warning: {name} not in conf", file=sys.stderr)
        continue
    asserts.append(f'static_assert(sizeof({ty}) == {vals[name]}, "{name}");')

# carry over local layout-accessor helpers defined inside the tool's main()
# (e.g. PrimitiveStringLayoutAccessor exposing private members via `using`)
helpers = "\n".join(
    m.group(0) for m in re.finditer(r"struct \w+LayoutAccessor[^;]*?\{.*?\};", src, re.S)
)

# the tool's main() runs inside namespace-using context; mirror it
body = "\n".join(asserts)
open(out_path, "w").write(f"""// generated by gen-offsets-check.py -- DO NOT EDIT
// compile-only: every static_assert is one AsmInt ABI assumption
{chr(10).join(includes)}
#include <cstddef>
using namespace JS;
using namespace JS::Bytecode;
{helpers}
{body}
int cc9_offsets_check_anchor;
""")
print(f"{len(asserts)} asserts -> {out_path}", file=sys.stderr)
