#!/usr/bin/env python3
"""
run9.py AOUT [--] [args...]   — deliver a Plan 9 a.out to the VM and run it WITH
arguments (deliver.py runs argv-less). stderr is merged into stdout so faults and
eprintln! output are visible. Config via env CC9_DEV="host port" (default
"127.0.0.1 1717").

    run9.py rust9/rgrep/target/x86_64-unknown-plan9/release/rgrep 'fn ' /sys/src
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "cc9", "host"))
from deliver import send  # reuse the listen1 byte-writer + run plumbing


def sh_quote(a: str) -> str:
    # rc quoting: wrap in single quotes, doubling embedded single quotes.
    return "'" + a.replace("'", "''") + "'"


def main():
    if len(sys.argv) < 2:
        print("usage: run9.py AOUT [args...]", file=sys.stderr)
        sys.exit(2)
    aout = sys.argv[1]
    prog_args = sys.argv[2:]
    if prog_args and prog_args[0] == "--":
        prog_args = prog_args[1:]

    host, port = (os.environ.get("CC9_DEV", "127.0.0.1 1717").split() + ["1717"])[:2]
    port = int(port)

    # Materialize the a.out on the box as /tmp/cc9bin via the generated byte-writer.
    data = open(aout, "rb").read()
    arr = ", ".join(f"0x{b:02x}" for b in data)
    writer = (
        "#include <u.h>\n#include <libc.h>\n"
        f"uchar data[] = {{{arr}}};\n"
        'void main(void){int fd=create("/tmp/cc9bin",OWRITE,0755);'
        "write(fd,data,sizeof data);close(fd);exits(nil);}\n"
    )
    ctimeout = int(os.environ.get("RUN9_CTIMEOUT", "300"))
    rtimeout = int(os.environ.get("RUN9_TIMEOUT", "60"))
    send(host, port, "cat > /tmp/cc9mk.c <<'XEOF'\n" + writer + "XEOF\necho W\n", ctimeout)
    send(host, port, "cd /tmp; 6c cc9mk.c\n", ctimeout)
    send(host, port, "cd /tmp; 6l -o cc9mk cc9mk.6\n", ctimeout)
    send(host, port, "/tmp/cc9mk >/dev/null >[2=1]\n", 60)

    cmd = "/tmp/cc9bin " + " ".join(sh_quote(a) for a in prog_args) + " >[2=1]\n"
    sys.stdout.write(send(host, port, cmd, rtimeout))


if __name__ == "__main__":
    main()
