#!/usr/bin/env python3
"""gen-confs.py — write one dosbox.conf per game, each with an [autoexec] that
mounts C: and launches the game.

Using a conf per game (rather than `dosbox -c "..."`) keeps us out of quoting
hell: the command has to survive rc, listen1, and gl9win2's argv, and every one
of those has its own opinion about quotes.

    python3 gen-confs.py /tmp/dosgames <guest-c-path>
"""
import os, sys

# slug -> (dos subdir, command to run)
GAMES = [
    ("keen1",   "KEEN1",   "KEEN1.EXE"),
    ("keen4",   "KEEN4",   "KEEN4E.EXE"),
    ("jill",    "JILL",    "JILL1.EXE"),
    ("raptor",  "RAPTOR",  "RAP.EXE"),
    ("blake",   "BLAKE",   "BS_AOG.EXE"),
    ("duke2",   "DUKE2",   "NUKEM2.EXE"),
    ("bmenace", "BMENACE", "BMENACE1.EXE"),
    ("caves",   "CAVES",   "CC1.EXE"),
    ("harry",   "HARRY",   "HH1.EXE"),
    ("hocus",   "HOCUS",   "HOCUS.EXE"),
    ("wolf3d",  "WOLF3D",  "WOLF3D.EXE"),
    ("doom",    "DOOM",    "DOOM.EXE"),
]

# cycles=max: let DOSBox use whatever the host can give.
#
# A fixed count would be more reproducible, but `fixed 20000` (~386DX) had
# DOSBox sleeping ~83% of the time on cirno while DOOM's R_Init crawled through
# a genuinely 386-speed startup. The emulated work is a fixed instruction
# count, so more cycles/ms == less wall clock. We're on the interpreter core
# (no dynrec), so there are cycles to spare.
CONF = """# generated by gen-confs.py — dosbox9 / 9front
[sdl]
fullscreen=false
output=surface
autolock=false
waitonerror=false

[dosbox]
machine=svga_s3
memsize=16

[cpu]
core=normal
cycles=max

[mixer]
nosound=false
rate=44100
blocksize=1024

[sblaster]
sbtype=sb16
oplmode=auto

[autoexec]
mount c {c}
c:
cd {sub}
{cmd}
"""


def main(dest, cpath):
    out = os.path.join(dest, "conf")
    os.makedirs(out, exist_ok=True)
    for slug, sub, cmd in GAMES:
        with open(os.path.join(out, f"{slug}.conf"), "w") as f:
            f.write(CONF.format(c=cpath, sub=sub, cmd=cmd))
    # a plain shell conf too, for poking around by hand
    with open(os.path.join(out, "shell.conf"), "w") as f:
        f.write(CONF.format(c=cpath, sub="\\", cmd="rem shell"))
    print(f"wrote {len(GAMES)+1} confs to {out} (C: -> {cpath})")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "/tmp/dosgames",
         sys.argv[2] if len(sys.argv) > 2 else "/tmp/d9/c")
